name: Générer et déployer une application .NET sur une application conteneur kmntontineapi-app-20250323172559
on:
  push:
    branches:
    - master
env:
  CONTAINER_APP_CONTAINER_NAME: kmntontineapi
  CONTAINER_APP_NAME: kmntontineapi-app-20250323172559
  CONTAINER_APP_RESOURCE_GROUP_NAME: DefaultResourceGroup-CCAN
  CONTAINER_REGISTRY_LOGIN_SERVER: kmntontineapi20250323173107.azurecr.io
  DOCKER_FILE_PATH: KMN_Tontine.API/Dockerfile
  PROJECT_NAME_FOR_DOCKER: kmn_tontine.api
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout to the branch
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.KMNTontineAPI20250323173107_USERNAME_9759 }}
        password: ${{ secrets.KMNTontineAPI20250323173107_PASSWORD_9759 }}
    - name: Build and push container image to registry
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }}
        file: ${{ env.DOCKER_FILE_PATH }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.kmntontineapi_app_20250323172559_SPN }}
    - name: Deploy to containerapp
      uses: azure/CLI@v2
      with:
        inlineScript: >
          az config set extension.use_dynamic_install=yes_without_prompt

          az containerapp registry set --name ${{ env.CONTAINER_APP_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --server ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }} --username ${{ secrets.KMNTontineAPI20250323173107_USERNAME_9759 }} --password ${{ secrets.KMNTontineAPI20250323173107_PASSWORD_9759 }}

          az containerapp update --name ${{ env.CONTAINER_APP_NAME }} --container-name ${{ env.CONTAINER_APP_CONTAINER_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --image ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }}
    - name: logout
      run: >
        az logout
