name: Trigger auto deployment for kmntontineapi-app-20250323172559

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/kmntontineapi-app-20250323172559-AutoDeployTrigger-7bf751cb-8061-4a85-b6d8-3ed65f4e7076.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.KMNTONTINEAPIAPP20250323172559_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: kmntontineapi20250323173107.azurecr.io
          registryUsername: ${{ secrets.KMNTONTINEAPIAPP20250323172559_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.KMNTONTINEAPIAPP20250323172559_REGISTRY_PASSWORD }}
          containerAppName: kmntontineapi-app-20250323172559
          resourceGroup: DefaultResourceGroup-CCAN
          imageToBuild: kmntontineapi20250323173107.azurecr.io/kmntontineapi-app-20250323172559:${{ github.sha }}
          
            

     

